name: fast_equatable
description: A simple Dart package that provides fast and secure equality comparison as a mixin. It optionally offers hash caching to improve the speed of Map's and Set's significantly.
version: 1.3.1
repository: https://github.com/FaFre/fast_equatable

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lint: ^2.1.2
  test: ^1.16.0
dependencies:
  collection: ^1.15.0
  meta: ^1.9.0
  xxh3: ^1.2.0
